import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const l10nDir = path.join(__dirname, 'src', 'resources', 'l10n');

// Comprehensive translations for ALL remaining languages
const translations = {
  'kk.json': {
    "routePlanner": "Маршрут жоспары",
    "routePlannerBasic": "Негізгі",
    "routePlannerEnterStartAddress": "Бастапқы мекенжайды енгізіңіз...",
    "routePlannerEnterAddress": "Мекенжайды енгізіңіз",
    "routePlannerEnterEndAddress": "Мақсат мекенжайын енгізіңіз...",
    "routePlannerAddAddress": "Мекенжай қосу",
    "routePlannerWaypoints": "Аралық нүктелер",
    "routePlannerRoutePlan": "Маршрут жоспары",
    "routePlannerDistance": "Қашықтық",
    "routePlannerDuration": "Ұзақтығы",
    "routePlannerSteps": "қадамдар",
    "routePlannerStep": "Қадам",
    "routePlannerPlanningRoute": "Маршрут жоспарлау...",
    "routePlannerSelectAddresses": "Маршрут жоспарлау үшін кемінде 2 мекенжай таңдаңыз",
    "routePlannerClickToPlan": "Маршрут жоспарлау үшін басыңыз",
    "routePlannerNotEnoughWaypoints": "Маршрут жоспарлау үшін жеткілікті аралық нүктелер жоқ"
  },
  'km.json': {
    "routePlanner": "អ្នករៀបចំផ្លូវ",
    "routePlannerBasic": "មូលដ្ឋាន",
    "routePlannerEnterStartAddress": "បញ្ចូលអាសយដ្ឋានចាប់ផ្តើម...",
    "routePlannerEnterAddress": "បញ្ចូលអាសយដ្ឋាន",
    "routePlannerEnterEndAddress": "បញ្ចូលអាសយដ្ឋានគោលដៅ...",
    "routePlannerAddAddress": "បន្ថែមអាសយដ្ឋាន",
    "routePlannerWaypoints": "ចំណុចឈប់",
    "routePlannerRoutePlan": "ផែនការផ្លូវ",
    "routePlannerDistance": "ចម្ងាយ",
    "routePlannerDuration": "រយៈពេល",
    "routePlannerSteps": "ជំហាន",
    "routePlannerStep": "ជំហាន",
    "routePlannerPlanningRoute": "កំពុងរៀបចំផ្លូវ...",
    "routePlannerSelectAddresses": "សូមជ្រើសរើសយ៉ាងហោចណាស់ 2 អាសយដ្ឋានដើម្បីរៀបចំផ្លូវ",
    "routePlannerClickToPlan": "ចុចដើម្បីរៀបចំផ្លូវ",
    "routePlannerNotEnoughWaypoints": "ចំណុចឈប់មិនគ្រប់គ្រាន់សម្រាប់ការរៀបចំផ្លូវ"
  },
  'lo.json': {
    "routePlanner": "ຜູ້ວາງແຜນທາງ",
    "routePlannerBasic": "ພື້ນຖານ",
    "routePlannerEnterStartAddress": "ໃສ່ທີ່ຢູ່ເລີ່ມຕົ້ນ...",
    "routePlannerEnterAddress": "ໃສ່ທີ່ຢູ່",
    "routePlannerEnterEndAddress": "ໃສ່ທີ່ຢູ່ປາຍທາງ...",
    "routePlannerAddAddress": "ເພີ່ມທີ່ຢູ່",
    "routePlannerWaypoints": "ຈຸດພັກ",
    "routePlannerRoutePlan": "ແຜນທາງ",
    "routePlannerDistance": "ໄລຍະຫ່າງ",
    "routePlannerDuration": "ໄລຍະເວລາ",
    "routePlannerSteps": "ຂັ້ນຕອນ",
    "routePlannerStep": "ຂັ້ນຕອນ",
    "routePlannerPlanningRoute": "ກຳລັງວາງແຜນທາງ...",
    "routePlannerSelectAddresses": "ກະລຸນາເລືອກຢ່າງໜ້ອຍ 2 ທີ່ຢູ່ເພື່ອວາງແຜນທາງ",
    "routePlannerClickToPlan": "ກົດເພື່ອວາງແຜນທາງ",
    "routePlannerNotEnoughWaypoints": "ຈຸດພັກບໍ່ພຽງພໍສຳລັບການວາງແຜນທາງ"
  },
  'lt.json': {
    "routePlanner": "Maršruto Planuotojas",
    "routePlannerBasic": "Pagrindinis",
    "routePlannerEnterStartAddress": "Įveskite pradžios adresą...",
    "routePlannerEnterAddress": "Įveskite adresą",
    "routePlannerEnterEndAddress": "Įveskite paskirties adresą...",
    "routePlannerAddAddress": "Pridėti Adresą",
    "routePlannerWaypoints": "Tarpinės stotelės",
    "routePlannerRoutePlan": "Maršruto planas",
    "routePlannerDistance": "Atstumas",
    "routePlannerDuration": "Trukmė",
    "routePlannerSteps": "žingsniai",
    "routePlannerStep": "Žingsnis",
    "routePlannerPlanningRoute": "Planuojamas maršrutas...",
    "routePlannerSelectAddresses": "Prašome pasirinkti bent 2 adresus maršruto planavimui",
    "routePlannerClickToPlan": "Spustelėkite maršruto planavimui",
    "routePlannerNotEnoughWaypoints": "Nepakanka tarpinių stočių maršruto planavimui"
  },
  'lv.json': {
    "routePlanner": "Maršruta Plānotājs",
    "routePlannerBasic": "Pamata",
    "routePlannerEnterStartAddress": "Ievadiet sākuma adresi...",
    "routePlannerEnterAddress": "Ievadiet adresi",
    "routePlannerEnterEndAddress": "Ievadiet galamērķa adresi...",
    "routePlannerAddAddress": "Pievienot Adresi",
    "routePlannerWaypoints": "Starpstacijas",
    "routePlannerRoutePlan": "Maršruta plāns",
    "routePlannerDistance": "Attālums",
    "routePlannerDuration": "Ilgums",
    "routePlannerSteps": "soļi",
    "routePlannerStep": "Solis",
    "routePlannerPlanningRoute": "Plāno maršrutu...",
    "routePlannerSelectAddresses": "Lūdzu, izvēlieties vismaz 2 adreses maršruta plānošanai",
    "routePlannerClickToPlan": "Noklikšķiniet maršruta plānošanai",
    "routePlannerNotEnoughWaypoints": "Nepietiek starpstaciju maršruta plānošanai"
  },
  'mk.json': {
    "routePlanner": "Планирач на Рути",
    "routePlannerBasic": "Основен",
    "routePlannerEnterStartAddress": "Внесете почетна адреса...",
    "routePlannerEnterAddress": "Внесете адреса",
    "routePlannerEnterEndAddress": "Внесете адреса на дестинацијата...",
    "routePlannerAddAddress": "Додај Адреса",
    "routePlannerWaypoints": "Меѓустојки",
    "routePlannerRoutePlan": "План на рутата",
    "routePlannerDistance": "Растојание",
    "routePlannerDuration": "Траење",
    "routePlannerSteps": "чекори",
    "routePlannerStep": "Чекор",
    "routePlannerPlanningRoute": "Планирање на рута...",
    "routePlannerSelectAddresses": "Ве молиме изберете најмалку 2 адреси за планирање на рута",
    "routePlannerClickToPlan": "Кликнете за планирање на рута",
    "routePlannerNotEnoughWaypoints": "Недоволно меѓустојки за планирање на рута"
  },
  'ml.json': {
    "routePlanner": "റൂട്ട് പ്ലാനർ",
    "routePlannerBasic": "അടിസ്ഥാന",
    "routePlannerEnterStartAddress": "ആരംഭ വിലാസം നൽകുക...",
    "routePlannerEnterAddress": "വിലാസം നൽകുക",
    "routePlannerEnterEndAddress": "ലക്ഷ്യ വിലാസം നൽകുക...",
    "routePlannerAddAddress": "വിലാസം ചേർക്കുക",
    "routePlannerWaypoints": "വഴിമുട്ടുകൾ",
    "routePlannerRoutePlan": "റൂട്ട് പ്ലാൻ",
    "routePlannerDistance": "ദൂരം",
    "routePlannerDuration": "കാലാവധി",
    "routePlannerSteps": "ഘട്ടങ്ങൾ",
    "routePlannerStep": "ഘട്ടം",
    "routePlannerPlanningRoute": "റൂട്ട് ആസൂത്രണം ചെയ്യുന്നു...",
    "routePlannerSelectAddresses": "റൂട്ട് ആസൂത്രണം ചെയ്യാൻ ദയവായി കുറഞ്ഞത് 2 വിലാസങ്ങൾ തിരഞ്ഞെടുക്കുക",
    "routePlannerClickToPlan": "റൂട്ട് ആസൂത്രണം ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക",
    "routePlannerNotEnoughWaypoints": "റൂട്ട് ആസൂത്രണത്തിന് മതിയായ വഴിമുട്ടുകൾ ഇല്ല"
  },
  'mn.json': {
    "routePlanner": "Зам төлөвлөгч",
    "routePlannerBasic": "Үндсэн",
    "routePlannerEnterStartAddress": "Эхлэх хаягийг оруулна уу...",
    "routePlannerEnterAddress": "Хаяг оруулна уу",
    "routePlannerEnterEndAddress": "Хаяг зорилго оруулна уу...",
    "routePlannerAddAddress": "Хаяг нэмэх",
    "routePlannerWaypoints": "Зогсоолын цэгүүд",
    "routePlannerRoutePlan": "Замны төлөвлөгөө",
    "routePlannerDistance": "Зай",
    "routePlannerDuration": "Хугацаа",
    "routePlannerSteps": "алхамууд",
    "routePlannerStep": "Алхам",
    "routePlannerPlanningRoute": "Зам төлөвлөж байна...",
    "routePlannerSelectAddresses": "Зам төлөвлөхийн тулд дор хаяж 2 хаяг сонгоно уу",
    "routePlannerClickToPlan": "Зам төлөвлөхийн тулд дарна уу",
    "routePlannerNotEnoughWaypoints": "Зам төлөвлөхийн тулд хангалттай зогсоолын цэг байхгүй"
  },
  'ms.json': {
    "routePlanner": "Perancang Laluan",
    "routePlannerBasic": "Asas",
    "routePlannerEnterStartAddress": "Masukkan alamat permulaan...",
    "routePlannerEnterAddress": "Masukkan alamat",
    "routePlannerEnterEndAddress": "Masukkan alamat destinasi...",
    "routePlannerAddAddress": "Tambah Alamat",
    "routePlannerWaypoints": "Titik Perhentian",
    "routePlannerRoutePlan": "Pelan Laluan",
    "routePlannerDistance": "Jarak",
    "routePlannerDuration": "Tempoh",
    "routePlannerSteps": "langkah",
    "routePlannerStep": "Langkah",
    "routePlannerPlanningRoute": "Merancang laluan...",
    "routePlannerSelectAddresses": "Sila pilih sekurang-kurangnya 2 alamat untuk merancang laluan",
    "routePlannerClickToPlan": "Klik untuk merancang laluan",
    "routePlannerNotEnoughWaypoints": "Titik perhentian tidak mencukupi untuk merancang laluan"
  },
  'nb.json': {
    "routePlanner": "Ruteplanlegger",
    "routePlannerBasic": "Grunnleggende",
    "routePlannerEnterStartAddress": "Skriv inn startadresse...",
    "routePlannerEnterAddress": "Skriv inn adresse",
    "routePlannerEnterEndAddress": "Skriv inn destinasjonsadresse...",
    "routePlannerAddAddress": "Legg til Adresse",
    "routePlannerWaypoints": "Mellomstopp",
    "routePlannerRoutePlan": "Ruteplan",
    "routePlannerDistance": "Avstand",
    "routePlannerDuration": "Varighet",
    "routePlannerSteps": "trinn",
    "routePlannerStep": "Trinn",
    "routePlannerPlanningRoute": "Planlegger rute...",
    "routePlannerSelectAddresses": "Vennligst velg minst 2 adresser for å planlegge en rute",
    "routePlannerClickToPlan": "Klikk for å planlegge rute",
    "routePlannerNotEnoughWaypoints": "Ikke nok mellomstopp for ruteplanlegging"
  },
  'ne.json': {
    "routePlanner": "मार्ग योजनाकार",
    "routePlannerBasic": "आधारभूत",
    "routePlannerEnterStartAddress": "सुरुको ठेगाना प्रविष्ट गर्नुहोस्...",
    "routePlannerEnterAddress": "ठेगाना प्रविष्ट गर्नुहोस्",
    "routePlannerEnterEndAddress": "गन्तव्य ठेगाना प्रविष्ट गर्नुहोस्...",
    "routePlannerAddAddress": "ठेगाना थप्नुहोस्",
    "routePlannerWaypoints": "बिचका बिन्दुहरू",
    "routePlannerRoutePlan": "मार्ग योजना",
    "routePlannerDistance": "दूरी",
    "routePlannerDuration": "अवधि",
    "routePlannerSteps": "चरणहरू",
    "routePlannerStep": "चरण",
    "routePlannerPlanningRoute": "मार्ग योजना गर्दै...",
    "routePlannerSelectAddresses": "कृपया मार्ग योजना गर्न कम्तिमा 2 ठेगाना छान्नुहोस्",
    "routePlannerClickToPlan": "मार्ग योजना गर्न क्लिक गर्नुहोस्",
    "routePlannerNotEnoughWaypoints": "मार्ग योजना गर्न पर्याप्त बिचका बिन्दुहरू छैनन्"
  },
  'nn.json': {
    "routePlanner": "Ruteplanleggjar",
    "routePlannerBasic": "Grunnleggjande",
    "routePlannerEnterStartAddress": "Skriv inn startadresse...",
    "routePlannerEnterAddress": "Skriv inn adresse",
    "routePlannerEnterEndAddress": "Skriv inn destinasjonsadresse...",
    "routePlannerAddAddress": "Legg til Adresse",
    "routePlannerWaypoints": "Mellomstopp",
    "routePlannerRoutePlan": "Ruteplan",
    "routePlannerDistance": "Avstand",
    "routePlannerDuration": "Varigheit",
    "routePlannerSteps": "steg",
    "routePlannerStep": "Steg",
    "routePlannerPlanningRoute": "Planlegg rute...",
    "routePlannerSelectAddresses": "Ver venleg vel minst 2 adresser for å planlegge ei rute",
    "routePlannerClickToPlan": "Klikk for å planlegge rute",
    "routePlannerNotEnoughWaypoints": "Ikkje nok mellomstopp for ruteplanlegging"
  },
  'ro.json': {
    "routePlanner": "Planificator de Rute",
    "routePlannerBasic": "De bază",
    "routePlannerEnterStartAddress": "Introduceți adresa de pornire...",
    "routePlannerEnterAddress": "Introduceți adresa",
    "routePlannerEnterEndAddress": "Introduceți adresa de destinație...",
    "routePlannerAddAddress": "Adăugați Adresă",
    "routePlannerWaypoints": "Puncte de oprire",
    "routePlannerRoutePlan": "Plan de rută",
    "routePlannerDistance": "Distanță",
    "routePlannerDuration": "Durată",
    "routePlannerSteps": "pași",
    "routePlannerStep": "Pas",
    "routePlannerPlanningRoute": "Planificare rută...",
    "routePlannerSelectAddresses": "Vă rugăm să selectați cel puțin 2 adrese pentru a planifica o rută",
    "routePlannerClickToPlan": "Faceți clic pentru a planifica ruta",
    "routePlannerNotEnoughWaypoints": "Puncte de oprire insuficiente pentru planificarea rutei"
  },
  'si.json': {
    "routePlanner": "මාර්ග සැලසුම්කරු",
    "routePlannerBasic": "මූලික",
    "routePlannerEnterStartAddress": "ආරම්භක ලිපිනය ඇතුළත් කරන්න...",
    "routePlannerEnterAddress": "ලිපිනය ඇතුළත් කරන්න",
    "routePlannerEnterEndAddress": "ගමනාන්ත ලිපිනය ඇතුළත් කරන්න...",
    "routePlannerAddAddress": "ලිපිනය එකතු කරන්න",
    "routePlannerWaypoints": "මාර්ග ලක්ෂ්‍ය",
    "routePlannerRoutePlan": "මාර්ග සැලසුම",
    "routePlannerDistance": "දුර",
    "routePlannerDuration": "කාලය",
    "routePlannerSteps": "පියවර",
    "routePlannerStep": "පියවර",
    "routePlannerPlanningRoute": "මාර්ග සැලසුම් කරමින්...",
    "routePlannerSelectAddresses": "මාර්ගයක් සැලසුම් කිරීම සඳහා කරුණාකර අවම වශයෙන් ලිපින 2ක් තෝරන්න",
    "routePlannerClickToPlan": "මාර්ගය සැලසුම් කිරීම සඳහා ක්ලික් කරන්න",
    "routePlannerNotEnoughWaypoints": "මාර්ග සැලසුම් කිරීම සඳහා ප්‍රමාණවත් මාර්ග ලක්ෂ්‍ය නොමැත"
  },
  'sk.json': {
    "routePlanner": "Plánovač Trás",
    "routePlannerBasic": "Základný",
    "routePlannerEnterStartAddress": "Zadajte počiatočnú adresu...",
    "routePlannerEnterAddress": "Zadajte adresu",
    "routePlannerEnterEndAddress": "Zadajte cieľovú adresu...",
    "routePlannerAddAddress": "Pridať Adresu",
    "routePlannerWaypoints": "Zastávky",
    "routePlannerRoutePlan": "Plán trasy",
    "routePlannerDistance": "Vzdialenosť",
    "routePlannerDuration": "Trvanie",
    "routePlannerSteps": "kroky",
    "routePlannerStep": "Krok",
    "routePlannerPlanningRoute": "Plánovanie trasy...",
    "routePlannerSelectAddresses": "Prosím, vyberte aspoň 2 adresy na plánovanie trasy",
    "routePlannerClickToPlan": "Kliknite na plánovanie trasy",
    "routePlannerNotEnoughWaypoints": "Nedostatok zastávok na plánovanie trasy"
  },
  'sl.json': {
    "routePlanner": "Načrtovalec Poti",
    "routePlannerBasic": "Osnovni",
    "routePlannerEnterStartAddress": "Vnesite začetni naslov...",
    "routePlannerEnterAddress": "Vnesite naslov",
    "routePlannerEnterEndAddress": "Vnesite ciljni naslov...",
    "routePlannerAddAddress": "Dodaj Naslov",
    "routePlannerWaypoints": "Vmesne postaje",
    "routePlannerRoutePlan": "Načrt poti",
    "routePlannerDistance": "Razdalja",
    "routePlannerDuration": "Trajanje",
    "routePlannerSteps": "koraki",
    "routePlannerStep": "Korak",
    "routePlannerPlanningRoute": "Načrtovanje poti...",
    "routePlannerSelectAddresses": "Prosimo, izberite vsaj 2 naslova za načrtovanje poti",
    "routePlannerClickToPlan": "Kliknite za načrtovanje poti",
    "routePlannerNotEnoughWaypoints": "Premalo vmesnih postaj za načrtovanje poti"
  },
  'sq.json': {
    "routePlanner": "Planifikuesi i Rrugës",
    "routePlannerBasic": "Bazë",
    "routePlannerEnterStartAddress": "Shkruani adresën e fillimit...",
    "routePlannerEnterAddress": "Shkruani adresën",
    "routePlannerEnterEndAddress": "Shkruani adresën e destinacionit...",
    "routePlannerAddAddress": "Shto Adresë",
    "routePlannerWaypoints": "Pikat e ndalimit",
    "routePlannerRoutePlan": "Plani i rrugës",
    "routePlannerDistance": "Distanca",
    "routePlannerDuration": "Kohëzgjatja",
    "routePlannerSteps": "hapa",
    "routePlannerStep": "Hap",
    "routePlannerPlanningRoute": "Planifikimi i rrugës...",
    "routePlannerSelectAddresses": "Ju lutemi zgjidhni të paktën 2 adresa për të planifikuar një rrugë",
    "routePlannerClickToPlan": "Klikoni për të planifikuar rrugën",
    "routePlannerNotEnoughWaypoints": "Pika të ndalimit të pamjaftueshme për planifikimin e rrugës"
  },
  'sr.json': {
    "routePlanner": "Планирач Рута",
    "routePlannerBasic": "Основни",
    "routePlannerEnterStartAddress": "Унесите почетну адресу...",
    "routePlannerEnterAddress": "Унесите адресу",
    "routePlannerEnterEndAddress": "Унесите адресу одредишта...",
    "routePlannerAddAddress": "Додај Адресу",
    "routePlannerWaypoints": "Стајалишта",
    "routePlannerRoutePlan": "План руте",
    "routePlannerDistance": "Удаљеност",
    "routePlannerDuration": "Трајање",
    "routePlannerSteps": "кораци",
    "routePlannerStep": "Корак",
    "routePlannerPlanningRoute": "Планирање руте...",
    "routePlannerSelectAddresses": "Молимо изаберите најмање 2 адресе за планирање руте",
    "routePlannerClickToPlan": "Кликните за планирање руте",
    "routePlannerNotEnoughWaypoints": "Недовољно стајалишта за планирање руте"
  },
  'sw.json': {
    "routePlanner": "Mpangaji wa Njia",
    "routePlannerBasic": "Msingi",
    "routePlannerEnterStartAddress": "Ingiza anwani ya kuanzia...",
    "routePlannerEnterAddress": "Ingiza anwani",
    "routePlannerEnterEndAddress": "Ingiza anwani ya marudio...",
    "routePlannerAddAddress": "Ongeza Anwani",
    "routePlannerWaypoints": "Vituo vya Kati",
    "routePlannerRoutePlan": "Mpango wa Njia",
    "routePlannerDistance": "Umbali",
    "routePlannerDuration": "Muda",
    "routePlannerSteps": "hatua",
    "routePlannerStep": "Hatua",
    "routePlannerPlanningRoute": "Kupanga njia...",
    "routePlannerSelectAddresses": "Tafadhali chagua angalau anwani 2 za kupanga njia",
    "routePlannerClickToPlan": "Bonyeza kupanga njia",
    "routePlannerNotEnoughWaypoints": "Vituo vya kati vya kutosha vya kupanga njia"
  },
  'ta.json': {
    "routePlanner": "வழி திட்டமிடுநர்",
    "routePlannerBasic": "அடிப்படை",
    "routePlannerEnterStartAddress": "தொடக்க முகவரியை உள்ளிடவும்...",
    "routePlannerEnterAddress": "முகவரியை உள்ளிடவும்",
    "routePlannerEnterEndAddress": "இலக்கு முகவரியை உள்ளிடவும்...",
    "routePlannerAddAddress": "முகவரியைச் சேர்க்கவும்",
    "routePlannerWaypoints": "வழிநிலை புள்ளிகள்",
    "routePlannerRoutePlan": "வழி திட்டம்",
    "routePlannerDistance": "தூரம்",
    "routePlannerDuration": "கால அளவு",
    "routePlannerSteps": "படிகள்",
    "routePlannerStep": "படி",
    "routePlannerPlanningRoute": "வழியை திட்டமிடுகிறது...",
    "routePlannerSelectAddresses": "வழியை திட்டமிட குறைந்தது 2 முகவரிகளை தேர்ந்தெடுக்கவும்",
    "routePlannerClickToPlan": "வழியை திட்டமிட கிளிக் செய்யவும்",
    "routePlannerNotEnoughWaypoints": "வழி திட்டமிட போதுமான வழிநிலை புள்ளிகள் இல்லை"
  },
  'tk.json': {
    "routePlanner": "Ýol Meýilnamaçy",
    "routePlannerBasic": "Esasy",
    "routePlannerEnterStartAddress": "Başlangyç salgysyny giriziň...",
    "routePlannerEnterAddress": "Salgysy giriziň",
    "routePlannerEnterEndAddress": "Niýetlenen salgysy giriziň...",
    "routePlannerAddAddress": "Salgy Goş",
    "routePlannerWaypoints": "Araçyklar",
    "routePlannerRoutePlan": "Ýol meýilnamasy",
    "routePlannerDistance": "Uzaklyk",
    "routePlannerDuration": "Dowamlylyk",
    "routePlannerSteps": "ädimler",
    "routePlannerStep": "Ädim",
    "routePlannerPlanningRoute": "Ýol meýilnama...",
    "routePlannerSelectAddresses": "Ýol meýilnama üçin iň az 2 salgy saýlaň",
    "routePlannerClickToPlan": "Ýol meýilnama üçin basyň",
    "routePlannerNotEnoughWaypoints": "Ýol meýilnama üçin ýeterlik araçyk ýok"
  },
  'uk.json': {
    "routePlanner": "Планувальник Маршрутів",
    "routePlannerBasic": "Базовий",
    "routePlannerEnterStartAddress": "Введіть початкову адресу...",
    "routePlannerEnterAddress": "Введіть адресу",
    "routePlannerEnterEndAddress": "Введіть адресу призначення...",
    "routePlannerAddAddress": "Додати Адресу",
    "routePlannerWaypoints": "Проміжні точки",
    "routePlannerRoutePlan": "План маршруту",
    "routePlannerDistance": "Відстань",
    "routePlannerDuration": "Тривалість",
    "routePlannerSteps": "кроки",
    "routePlannerStep": "Крок",
    "routePlannerPlanningRoute": "Планування маршруту...",
    "routePlannerSelectAddresses": "Будь ласка, оберіть принаймні 2 адреси для планування маршруту",
    "routePlannerClickToPlan": "Натисніть для планування маршруту",
    "routePlannerNotEnoughWaypoints": "Недостатньо проміжних точок для планування маршруту"
  },
  'uz.json': {
    "routePlanner": "Marshrut Rejalashtiruvchi",
    "routePlannerBasic": "Asosiy",
    "routePlannerEnterStartAddress": "Boshlang'ich manzilni kiriting...",
    "routePlannerEnterAddress": "Manzilni kiriting",
    "routePlannerEnterEndAddress": "Maqsad manzilini kiriting...",
    "routePlannerAddAddress": "Manzil Qo'shish",
    "routePlannerWaypoints": "Oraliq nuqtalar",
    "routePlannerRoutePlan": "Marshrut rejasi",
    "routePlannerDistance": "Masofa",
    "routePlannerDuration": "Davomiyligi",
    "routePlannerSteps": "qadamlar",
    "routePlannerStep": "Qadam",
    "routePlannerPlanningRoute": "Marshrut rejalashtirilmoqda...",
    "routePlannerSelectAddresses": "Marshrut rejalashtirish uchun kamida 2 ta manzil tanlang",
    "routePlannerClickToPlan": "Marshrut rejalashtirish uchun bosing",
    "routePlannerNotEnoughWaypoints": "Marshrut rejalashtirish uchun etarli oraliq nuqtalar yo'q"
  },
  'zh_TW.json': {
    "routePlanner": "路線規劃器",
    "routePlannerBasic": "基本",
    "routePlannerEnterStartAddress": "輸入起始地址...",
    "routePlannerEnterAddress": "輸入地址",
    "routePlannerEnterEndAddress": "輸入目的地地址...",
    "routePlannerAddAddress": "新增地址",
    "routePlannerWaypoints": "途經點",
    "routePlannerRoutePlan": "路線計劃",
    "routePlannerDistance": "距離",
    "routePlannerDuration": "時長",
    "routePlannerSteps": "步驟",
    "routePlannerStep": "步驟",
    "routePlannerPlanningRoute": "正在規劃路線...",
    "routePlannerSelectAddresses": "請選擇至少2個地址來規劃路線",
    "routePlannerClickToPlan": "點擊規劃路線",
    "routePlannerNotEnoughWaypoints": "途經點不足，無法規劃路線"
  }
};

// Process each language file
Object.keys(translations).forEach(filename => {
  const filePath = path.join(l10nDir, filename);
  
  if (fs.existsSync(filePath)) {
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      const data = JSON.parse(content);
      
      // Replace English placeholders with proper translations
      Object.assign(data, translations[filename]);
      
      // Write back to file
      fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
      console.log(`✅ Fixed translations for ${filename}`);
    } catch (error) {
      console.error(`❌ Error processing ${filename}:`, error.message);
    }
  } else {
    console.log(`⚠️  File not found: ${filename}`);
  }
});

console.log('🎉 ALL remaining translations fixed!');
